# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Improving Detection Performance with SAHI and Tiled Predictions
author: RidgeRun.ai
logo: https://static.wixstatic.com/media/3e14fd_7c4b0fa04d8041789585fd6e502325e8%7Emv2.png/v1/fill/w_32%2Ch_32%2Clg_1%2Cusm_0.66_1.00_0.01/3e14fd_7c4b0fa04d8041789585fd6e502325e8%7Emv2.png
copyright: "2024"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: "auto"

html:
  favicon: https://static.wixstatic.com/media/3e14fd_7c4b0fa04d8041789585fd6e502325e8%7Emv2.png/v1/fill/w_32%2Ch_32%2Clg_1%2Cusm_0.66_1.00_0.01/3e14fd_7c4b0fa04d8041789585fd6e502325e8%7Emv2.png
#  home_page_in_navbar: false
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true

# Information about where the book exists on the web
repository:
  url: https://github.com/ridgerun-ai/sahi-tutorial
  branch: main

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

launch_buttons:
  notebook_interface: "classic"
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"
  thebe: true
